[project]
name = "psnv"
version = "0.1.0"
authors = [{ name = "kahosan", email = "15116355657l@gmail.com" }]
description = ""
readme = "README.md"
license = "MIT"
requires-python = ">=3.13"
dependencies = [
    "pixivpy3>=3.7.5",
    "rich>=14.0.0",
]
